/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    posts: Post;
    pages: Page;
    leads: Lead;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  bio?: string | null;
  profileImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    article?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  author?: (number | null) | User;
  category?: (number | null) | Category;
  featureImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Defaults to 'Frequently Asked Questions' when empty.
   */
  faqHeading?: string | null;
  faqs?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  focusKeyphrase?: string | null;
  /**
   * Manually enter JSON-LD structured data for this post (e.g. Article, FAQPage schema).
   */
  jsonSchema?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  publishedDate?: string | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Internal page label and fallback SEO title.
   */
  title: string;
  /**
   * Path this page is served from, e.g. fleet-management.
   */
  slug: string;
  /**
   * Falls back to the page title.
   */
  metaTitle?: string | null;
  metaDescription?: string | null;
  /**
   * Drag to reorder. The page renders these sections top to bottom.
   */
  blocks?:
    | (
        | {
            heading: string;
            description: string;
            /**
             * Full-bleed background behind the gradient overlay. Landscape works best.
             */
            backgroundImage: number | Media;
            highlights: {
              text: string;
              id?: string | null;
            }[];
            /**
             * Optional. Up to four fit in a single row.
             */
            reviews?:
              | {
                  /**
                   * Optional. When empty, the text label is shown instead.
                   */
                  logo?: (number | null) | Media;
                  alt?: string | null;
                  /**
                   * Fallback text rating, e.g. Trustpilot 4.8.
                   */
                  label?: string | null;
                  /**
                   * Optional. Any string, e.g. ★★★★★ or 4.8/5.
                   */
                  rating?: string | null;
                  id?: string | null;
                }[]
              | null;
            formHeading: string;
            namePlaceholder: string;
            phonePlaceholder: string;
            emailPlaceholder: string;
            organizationPlaceholder: string;
            buttonText: string;
            variant?: ('default' | 'compact') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'serviceHero';
          }
        | {
            heading: string;
            /**
             * Cards are laid out in a responsive grid that widens as the list grows.
             */
            items: {
              title: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'simpleFeatureCards';
          }
        | {
            heading: string;
            /**
             * Shown beside the list. A portrait or square image works best.
             */
            image: number | Media;
            /**
             * Falls back to the alt text of the selected media file.
             */
            imageAlt?: string | null;
            services: {
              title: string;
              description: string;
              /**
               * Highlights this item with an accent border and badge.
               */
              highlighted?: boolean | null;
              id?: string | null;
            }[];
            variant?: ('default' | 'compact') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'serviceGridWithImage';
          }
        | {
            heading: string;
            faqs: {
              question: string;
              /**
               * Plain text. Line breaks are preserved.
               */
              answer: string;
              id?: string | null;
            }[];
            /**
             * Zero-based index of the question shown expanded. Use -1 to keep all closed.
             */
            defaultOpenIndex?: number | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqSection';
          }
        | {
            heading: string;
            description: string;
            /**
             * Sits behind the teal overlay. Landscape works best.
             */
            backgroundImage: number | Media;
            primaryButtonText: string;
            primaryButtonHref: string;
            secondaryButtonText: string;
            secondaryButtonHref: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'revenueCTA';
          }
        | {
            heading: string;
            /**
             * Shown in the tinted panel next to the heading. Line breaks are preserved.
             */
            intro: string;
            image: number | Media;
            /**
             * Falls back to the alt text of the selected media file.
             */
            imageAlt?: string | null;
            /**
             * Short statements listed beside the image.
             */
            points: {
              text: string;
              id?: string | null;
            }[];
            /**
             * Long-form column on the right.
             */
            story: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'aboutOverview';
          }
        | {
            heading: string;
            description: string;
            /**
             * Sits behind the teal panel. Landscape works best.
             */
            backgroundImage: number | Media;
            /**
             * Cut-out portrait shown overlapping the bottom right corner. A person with a transparent background works best.
             */
            doctorImage: number | Media;
            /**
             * Falls back to the alt text of the selected media file.
             */
            doctorImageAlt?: string | null;
            buttons: {
              label: string;
              href: string;
              variant?: ('primary' | 'secondary') | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'aboutUsCTA';
          }
        | {
            /**
             * Image and text alternate sides automatically based on order.
             */
            items: {
              title: string;
              description: string;
              image: number | Media;
              /**
               * Falls back to the alt text of the selected media file.
               */
              imageAlt?: string | null;
              bullets?:
                | {
                    text: string;
                    id?: string | null;
                  }[]
                | null;
              /**
               * Optional closing line under the bullets.
               */
              footerText?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'alternatingServices';
          }
        | {
            heading: string;
            challenges: {
              title: string;
              description: string;
              /**
               * Square icon, ideally a transparent PNG or SVG.
               */
              icon: number | Media;
              iconAlt?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'billingChallenges';
          }
        | {
            heading: string;
            image: number | Media;
            /**
             * Falls back to the alt text of the selected media file.
             */
            imageAlt?: string | null;
            steps: {
              /**
               * Displayed large beside the step, e.g. 01.
               */
              number: string;
              title: string;
              description: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'billingProcess';
          }
        | {
            /**
             * Optional. The table is shown on its own when empty.
             */
            heading?: string | null;
            featureHeading: string;
            avenueHeading: string;
            comparisonHeading: string;
            rows: {
              feature: string;
              avenue: string;
              comparison: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'comparisonTable';
          }
        | {
            heading: string;
            /**
             * Optional line under the heading.
             */
            subtitle?: string | null;
            /**
             * Displayed in diamond cards, four per row.
             */
            items: {
              text: string;
              id?: string | null;
            }[];
            /**
             * Optional bold line under the cards.
             */
            footerText?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'complianceCommitment';
          }
        | {
            heading: string;
            image: number | Media;
            /**
             * Falls back to the alt text of the selected media file.
             */
            imageAlt?: string | null;
            /**
             * The first value is expanded by default.
             */
            values: {
              title: string;
              /**
               * Only shown for the expanded value.
               */
              description?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'coreValues';
          }
        | {
            heading: string;
            /**
             * Optional line under the heading.
             */
            description?: string | null;
            /**
             * Up to seven. The first four fill the top row, the rest the second row.
             */
            categories: {
              title: string;
              description?: string | null;
              highlighted?: boolean | null;
              id?: string | null;
            }[];
            variant?: ('default' | 'stats') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'denialCategories';
          }
        | {
            heading: string;
            description: string;
            partners: {
              /**
               * Wide logo, ideally on a transparent background.
               */
              logo: number | Media;
              alt?: string | null;
              id?: string | null;
            }[];
            /**
             * Optional line under the logos.
             */
            bottomText?: string | null;
            buttonText?: string | null;
            buttonHref?: string | null;
            variant?: ('default' | 'compact') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ehrPartners';
          }
        | {
            heading: string;
            cards: {
              title: string;
              /**
               * Short reference shown under the title, e.g. A/R or CPT.
               */
              code: string;
              description: string;
              highlighted?: boolean | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'expertiseCards';
          }
        | {
            heading: string;
            testimonials: {
              name: string;
              /**
               * Shown under the name, e.g. Practice Manager.
               */
              role: string;
              image: number | Media;
              /**
               * Falls back to the alt text of the selected media file.
               */
              imageAlt?: string | null;
              /**
               * Wide star rating graphic, shown small under the role.
               */
              ratingImage: number | Media;
              /**
               * e.g. Rated 5 out of 5.
               */
              ratingAlt?: string | null;
              /**
               * Displayed with surrounding quotation marks.
               */
              quote: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            heading: string;
            /**
             * Up to four columns. Each column holds a group of label and value pairs.
             */
            columns: {
              items: {
                label: string;
                /**
                 * Highlighted figure, e.g. 98% or $4.2M.
                 */
                value: string;
                id?: string | null;
              }[];
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'successNumbers';
          }
        | {
            heading: string;
            items: {
              title: string;
              description: string;
              highlighted?: boolean | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'textFeatureGrid';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Form submissions received from the website. Use Queries by Page to review submissions by their source page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  message?: string | null;
  /**
   * The website URL path the submission came from, e.g. /contact.
   */
  pagePath?: string | null;
  /**
   * Context label sent by the form, e.g. 'Texas CTA Lead'.
   */
  sourcePage?: string | null;
  submissionType?: ('contact-form' | 'lead-capture' | 'state-picker' | 'service-picker' | 'schedule-call') | null;
  status: 'new' | 'in-progress' | 'done' | 'cancelled';
  handledBy?: string | null;
  handledAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  bio?: T;
  profileImage?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        article?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  author?: T;
  category?: T;
  featureImage?: T;
  content?: T;
  faqHeading?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  metaTitle?: T;
  metaDescription?: T;
  focusKeyphrase?: T;
  jsonSchema?: T;
  publishedDate?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  metaTitle?: T;
  metaDescription?: T;
  blocks?:
    | T
    | {
        serviceHero?:
          | T
          | {
              heading?: T;
              description?: T;
              backgroundImage?: T;
              highlights?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              reviews?:
                | T
                | {
                    logo?: T;
                    alt?: T;
                    label?: T;
                    rating?: T;
                    id?: T;
                  };
              formHeading?: T;
              namePlaceholder?: T;
              phonePlaceholder?: T;
              emailPlaceholder?: T;
              organizationPlaceholder?: T;
              buttonText?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        simpleFeatureCards?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        serviceGridWithImage?:
          | T
          | {
              heading?: T;
              image?: T;
              imageAlt?: T;
              services?:
                | T
                | {
                    title?: T;
                    description?: T;
                    highlighted?: T;
                    id?: T;
                  };
              variant?: T;
              id?: T;
              blockName?: T;
            };
        faqSection?:
          | T
          | {
              heading?: T;
              faqs?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              defaultOpenIndex?: T;
              id?: T;
              blockName?: T;
            };
        revenueCTA?:
          | T
          | {
              heading?: T;
              description?: T;
              backgroundImage?: T;
              primaryButtonText?: T;
              primaryButtonHref?: T;
              secondaryButtonText?: T;
              secondaryButtonHref?: T;
              id?: T;
              blockName?: T;
            };
        aboutOverview?:
          | T
          | {
              heading?: T;
              intro?: T;
              image?: T;
              imageAlt?: T;
              points?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              story?: T;
              id?: T;
              blockName?: T;
            };
        aboutUsCTA?:
          | T
          | {
              heading?: T;
              description?: T;
              backgroundImage?: T;
              doctorImage?: T;
              doctorImageAlt?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    href?: T;
                    variant?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        alternatingServices?:
          | T
          | {
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    imageAlt?: T;
                    bullets?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    footerText?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        billingChallenges?:
          | T
          | {
              heading?: T;
              challenges?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    iconAlt?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        billingProcess?:
          | T
          | {
              heading?: T;
              image?: T;
              imageAlt?: T;
              steps?:
                | T
                | {
                    number?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        comparisonTable?:
          | T
          | {
              heading?: T;
              featureHeading?: T;
              avenueHeading?: T;
              comparisonHeading?: T;
              rows?:
                | T
                | {
                    feature?: T;
                    avenue?: T;
                    comparison?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        complianceCommitment?:
          | T
          | {
              heading?: T;
              subtitle?: T;
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              footerText?: T;
              id?: T;
              blockName?: T;
            };
        coreValues?:
          | T
          | {
              heading?: T;
              image?: T;
              imageAlt?: T;
              values?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        denialCategories?:
          | T
          | {
              heading?: T;
              description?: T;
              categories?:
                | T
                | {
                    title?: T;
                    description?: T;
                    highlighted?: T;
                    id?: T;
                  };
              variant?: T;
              id?: T;
              blockName?: T;
            };
        ehrPartners?:
          | T
          | {
              heading?: T;
              description?: T;
              partners?:
                | T
                | {
                    logo?: T;
                    alt?: T;
                    id?: T;
                  };
              bottomText?: T;
              buttonText?: T;
              buttonHref?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        expertiseCards?:
          | T
          | {
              heading?: T;
              cards?:
                | T
                | {
                    title?: T;
                    code?: T;
                    description?: T;
                    highlighted?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              heading?: T;
              testimonials?:
                | T
                | {
                    name?: T;
                    role?: T;
                    image?: T;
                    imageAlt?: T;
                    ratingImage?: T;
                    ratingAlt?: T;
                    quote?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        successNumbers?:
          | T
          | {
              heading?: T;
              columns?:
                | T
                | {
                    items?:
                      | T
                      | {
                          label?: T;
                          value?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        textFeatureGrid?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    highlighted?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  pagePath?: T;
  sourcePage?: T;
  submissionType?: T;
  status?: T;
  handledBy?: T;
  handledAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}